[workspace]
resolver = "2"
members = ["summa-core", "summa-proto", "summa-publisher", "summa-server", "summa-wasm"]

[profile.release]
lto = true
strip = "debuginfo"

[workspace.dependencies]
tantivy = { git = "https://github.com/izihawa/tantivy", branch = "feature/pub-rayon", version = "0.19.0", default_features = false, features = ["quickwit", "zstd-compression"]}
iroh-api = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-gateway = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-metrics = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-p2p = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-resolver = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-rpc-client = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-rpc-types = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-store = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
iroh-unixfs = { git = "https://github.com/izihawa/iroh", branch = "feature/summa", version = "0.2.0" }
tokio = { version = "1.24", features = ["full", "time"] }