[workspace]
resolver = "2"
members = ["summa-proto", "summa-core", "summa-server", "summa-wasm"]

[profile.release]
lto = true

[workspace.dependencies]
tantivy = { git = "https://github.com/izihawa/tantivy", branch = "feature/pub-rayon", package = "summavy", version = "0.24.0", default_features = false, features = ["quickwit", "zstd-compression"]}
