[package]
name = "summa-wasm"
version = "0.66.0"
authors = ["Pasha Podolsky <ppodolsky@me.com>"]
edition = "2021"
license-file = "LICENSE"
description = "WASM bindings for Summa"
homepage = "https://github.com/izihawa/summa"
repository = "https://github.com/izihawa/summa"
readme = "README.md"
keywords = ["async", "search", "wasm", "web"]

[lib]
crate-type = ["cdylib", "rlib"]
path = "crate/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
async-trait = "0.1"
console_error_panic_hook = { version = "0.1", optional = true }
futures = "0.3"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
once_cell = "1.16"
rayon = "1.5"
serde = "1.0"
serde_json = "1.0"
serde-wasm-bindgen = "0.4"
spmc = "0.3"
strfmt = "0.2"
summa-core = { version = "0.11", path = "../summa-core", default_features = false }
summa-proto = { version = "0.11", path = "../summa-proto", default_features = false }
tantivy = { workspace = true }
thiserror = "1.0"
tokio = { version = "1.23", default_features = false, features = ["macros", "rt", "signal-hook-registry", "sync"] }
tracing = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console"] }
wee_alloc = "0.4.5"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--detect-features", "-O3", "--enable-mutable-globals"]
