[package]
name = "summa-wasm"
version = "0.37.1"
authors = ["Pasha Podolsky <ppodolsky@me.com>"]
edition = "2021"
license-file = "LICENSE"
description = "WASM bindings for Summa"
homepage = "https://github.com/izihawa/summa"
repository = "https://github.com/izihawa/summa"
readme = "README.md"
keywords = ["async", "search", "wasm", "web"]

[lib]
crate-type = ["cdylib", "rlib"]
path = "crate/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
async-trait = "0.1.57"
console_error_panic_hook = { version = "0.1.6", optional = true }
futures = "0.3.24"
getrandom = { version = "0.2.7", features = ["js"] }
js-sys = "0.3.60"
once_cell = "1.15.0"
rayon = "1.5.3"
serde = "1.0.144"
serde_json = "1.0.85"
serde-wasm-bindgen = "0.4.3"
spmc = "0.3.0"
strfmt = "0.2.2"
summa-core = { version = "0.10.0", path = "../summa-core", default_features = false }
summa-proto = { version = "0.10.0", path = "../summa", default_features = false }
tantivy = { package = "summavy", version = "0.19.9", default_features = false, features = ["quickwit", "zstd-compression"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", default_features = false, features = ["macros", "rt", "signal-hook-registry", "sync"] }
tracing = "0.1.36"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3.60", features = ["console"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--detect-features", "-Os", "--enable-mutable-globals"]
