[package]
name = "summa-core"
version = "0.11.0"
authors = ["Pasha Podolsky <ppodolsky@me.com>"]
edition = "2021"
license-file = "LICENSE"
description = "Summa core library"

[lib]
name = "summa_core"
path = "src/lib.rs"
doc = true

[features]
fs = ["tantivy/mmap", "tokio/fs"]
ipfs = ["iroh-api", "iroh-metrics", "iroh-resolver", "iroh-rpc-client", "iroh-unixfs"]
metrics = ["opentelemetry"]

[dependencies]
anyhow = "1.0.68"
async-broadcast = "0.4"
async-trait = "0.1"
base64 = "0.20.0"
config = "0.13"
crossbeam-channel = "0.5"
derive_builder = "0.12"
fasteval2 = { version = "2.0", features = ["unsafe-vars"] }
futures = "0.3"
instant = { version = "0.1", default_features = false, features = [ "inaccurate", "wasm-bindgen" ] }
iroh-api = { workspace = true, optional = true }
iroh-metrics = { workspace = true, optional = true }
iroh-resolver = { workspace = true, optional = true }
iroh-rpc-client = { workspace = true, optional = true }
iroh-unixfs = { workspace = true, optional = true }
itertools = "0.10"
lazy_static = "1.4"
lru = "0.8"
once_cell = "1.16"
opentelemetry = { version = "0.18", features = ["rt-tokio"], optional = true }
prost = "0.11"
rand = { version = "0.8", features = ["small_rng"] }
rayon = "1.6.0"
rustc-hash = "1.1"
serde = { version = "1.0", default_features = false, features = ["derive", "std"] }
serde_cbor = "0.11"
serde_json = "1.0"
serde_yaml = "0.8"
strfmt = "0.2.2"
summa-proto = { version = "0.11.0", path = "../summa-proto", default_features = false }
take_mut = "0.2"
tantivy = { workspace = true }
thiserror = "1.0"
time = { version = "0.3.14", features = ["serde-well-known", "wasm-bindgen"] }
tokio = { version = "1.21.2", default_features = false, features = ["macros", "rt", "signal-hook-registry", "sync"] }
tracing = "0.1"
