[package]
name = "summa-core"
version = "0.11.0"
authors = ["Pasha Podolsky <ppodolsky@me.com>"]
edition = "2021"
license-file = "LICENSE"
description = "Summa core library"

[lib]
name = "summa_core"
path = "src/lib.rs"
doc = true

[features]
fs = ["tokio/fs"]
consume = ["rdkafka"]
metrics = ["opentelemetry", "opentelemetry-prometheus"]
test-utils = []

[dependencies]
async-broadcast = "0.4.1"
async-trait = "0.1.57"
base64 = "0.13.0"
config = "0.13.2"
crossbeam-channel = "0.5.6"
derive_builder = "0.11.2"
fasteval2 = { version = "2.0.6", features = ["unsafe-vars"] }
futures = "0.3.24"
instant = { version = "0.1", default_features = false, features = [ "inaccurate", "wasm-bindgen" ] }
itertools = "0.10.5"
lazy_static = "1.4.0"
lru = "0.8.1"
once_cell = "1.15.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"], optional = true }
opentelemetry-prometheus = { version = "0.11.0", optional = true }
path-absolutize = { version = "3.0.14", features = ["use_unix_paths_on_wasm"] }
prost = "0.11.0"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.5.3"
rdkafka = { version = "0.29.0", optional = true }
rustc-hash = "1.1.0"
serde = { version = "1.0.140", default_features = false, features = ["derive", "std"] }
serde_cbor = "0.11.2"
serde_json = "1.0.85"
serde_yaml = "0.8.26"
strfmt = "0.2.2"
summa-proto = { version = "0.11.0", path = "../summa-proto", default_features = false }
take_mut = "0.2.2"
tantivy = { package = "summavy", version = "0.22.0", path = "../../tantivy", default_features = false, features = ["quickwit", "zstd-compression"] }
thiserror = "1.0.36"
time = { version = "0.3.14", features = ["serde-well-known", "wasm-bindgen"] }
tokio = { version = "1.21.2", default_features = false, features = ["macros", "rt", "signal-hook-registry", "sync"] }
tracing = "0.1.37"
web-sys = { version = "0.3.60", features = ["console"] }
