# yamllint disable

name: Release
on:
  release:
    types: [ published ]
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: publish -p summa-proto
          args: --verbose
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: publish -p summa-core
          args: --verbose
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: publish -p summa-server
          args: --verbose
  push-to-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - uses: actions/cache@v2.1.6
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: DOCKER_CONFIG=$HOME/.docker summa-server/push-to-docker.sh
